### ISSUE TITLE
Evoluzione demo interfaccia

### ISSUE THREAD

**Issue by Giambapisasale** [Giambapisasale/WP-Angular-Bootstrap#1]
## Evoluzione interfaccia sito
* Il caricamento di articoli sembra ok, verificare la presenza di media
* Gestire "sezioni" diverse del sito che possono avere un layout e stile grafico differente

**Comment by ShinDarth** [comment]
La prima è stata risolta da Stefano @Helias , per la seconda credo sufficiente utilizzare i partials, così come abbiamo assegnato un template indipendente per post, categorie, pagine, autori, etc...

**Comment by Giambapisasale** [comment]
Ottimo lavoro ragazzi!

**Comment by Giambapisasale** [comment]
Riaperta perchè manca evidenza di come cambiano layout e grafica tra post / pagine / categorie

**Comment by ShinDarth** [comment]
https://github.com/Giambapisasale/WP-Angular-Bootstrap/commit/c2bd99716aeb9d167a46c83395c3350f7ee34d80
