### ISSUE TITLE
Menu dinamici

### ISSUE THREAD

**Issue by ShinDarth** [Giambapisasale/WP-Angular-Bootstrap#3]
1) La lista delle voci dei menu deve venire da WordPress
2) Gestire menu multipli (scegliere quale menu di wp visualizzare)
3) Gestire sottomenu differenti per ogni sezione del sito

**Comment by ShinDarth** [comment]
@Giambapisasale 
La 1) l'abbiamo fatta, la 3) è come la 1) (in pratica i menu vanno messi nei partials file, piuttosto che nell'index come avviene attualmente). Per quanto riguarda la 2) invece, la scelta di quale menù di wp visualizzare come dev'essere fatta? Cioè dove avviene questa scelta?

**Comment by Giambapisasale** [comment]
Bene, se avete committato i file e il dump posso verificare.
Per gli altri punti lo scenario è quello di un normale sito, prendete spunto da www.comune.catania.it, ogni sezione hai i suoi menu.
Trovate il modo per impostare in wordpress la stessa gestione dei menu e di conseguenza dovete trovare il modo per visualizzarli a frontend, dove per ogni menu ci possono essere sottomenu e ogni sezione del sito può avere un suo menu (wordpress permette di creare quanti menu si vuole)
