### ISSUE TITLE
Verificare e eventualmente migliorare restore/dump db wp

### ISSUE THREAD

**Issue by ShinDarth** [Giambapisasale/WP-Angular-Bootstrap#5]
1) Restore del dump di @fabiofebo
2) Aggiornare wordpress/README con eventuali indicazioni
3) Importare nuovo plugin (vedi issue #3 )
4) Committare file di wordpress modificati
5) Creare dump con script di @fabiofebo 
6) Committare dump e aggiornare wordpress/README con eventuali indicazioni

**Comment by ShinDarth** [comment]
Fatti tutti tranne il 3)

**Comment by ShinDarth** [comment]
Fatto anche il 3, plugin importato: https://github.com/nekojira/wp-api-menus

**Comment by Giambapisasale** [comment]
manca il file .bat per windows

**Comment by Giambapisasale** [comment]
sistemare la gestione dell'utente nel restore, utilizzare un solo utente che deve già essere configurato
il nome del database deve essere configurabile
